# start name:common
services:
  # start name:redpanda
  redpanda-0:
    image: redpandadata/redpanda:v25.3.10
    container_name: redpanda-0
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    environment:
      RP_BOOTSTRAP_USER: "superuser:secretpassword"
    volumes:
      - redpanda-0:/var/lib/redpanda/data
    configs:
      - source: bootstrap
        target: /etc/redpanda/.bootstrap.yaml
    networks:
      - redpanda_network
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    healthcheck:
      test: [ "CMD", "rpk", "cluster", "info", "-X", "user=superuser", "-X", "pass=secretpassword" ]
      interval: 5s
      timeout: 15s
      retries: 5

  createtopic:
    image: redpandadata/redpanda:v25.3.10
    command:
      - topic
      - create
      - example-topic
      - -X user=superuser
      - -X pass=secretpassword
      - -X brokers=redpanda-0:9092
    networks:
      - redpanda_network
    depends_on:
      redpanda-0:
        condition: service_healthy

  console:
    image: redpandadata/console:v3.6.0
    container_name: redpanda-console
    networks:
      - redpanda_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml && /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-0:9092"]
          sasl:
            enabled: true
            impersonateUser: true
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda-0:8081"]
          authentication:
            impersonateUser: true
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-0:9644"]
            authentication:
              basic:
                username: superuser
                password: secretpassword
              impersonateUser: false
        authentication:
          jwtSigningKey: vazxnT+ZHtxKslK6QlDGovcYnSjTk/lKMmZ+mHrBVE+YdVDkLgSuP6AszAKe9Gvq
          basic:
            enabled: true
        authorization:
          roleBindings:
          - roleName: admin
            users:
              - loginType: basic
                name: superuser
        analytics:
          enabled: false
    ports:
      - 8081:8080
    depends_on:
      redpanda-0:
        condition: service_healthy

networks:
  redpanda_network:
    driver: bridge
volumes:
  redpanda-0: null
configs:
  bootstrap:
    content: |
      admin_api_require_auth: true
      superusers:
        - superuser
      enable_sasl: true