version: '3'

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build project
    cmds:
      - go build -o bin/server ./cmd/server

  run:
    desc: Run project
    cmds:
      - go run ./cmd/server

  test:
    desc: Run tests
    cmds:
      - go test ./...

  install-golangci-lint:
    desc: Install golangci-lint
    run: once
    env:
      GOBIN:
        sh: "echo `pwd`/bin"
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.3

  lint:
    desc: Run linter
    deps:
      - install-golangci-lint
    cmds:
      - go fmt ./...
      - go vet ./...
      - bin/golangci-lint run
